"""Generate ParaView Python scene scripts for Zigbee activity exports.

The generated script is meant to be run with ParaView's Python interpreter:

    pvpython capture_paraview_scene.py

or opened from ParaView with File > Open and then run in the Python Shell.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ParaViewSceneConfig:
    """Rendering options embedded into a generated ParaView scene script."""

    point_color_by: str = "activity_id"
    volume_color_by: str = "dominant_activity_id"
    point_size: float = 6.0
    point_opacity: float = 0.85
    volume_opacity: float = 0.18
    screenshot_size: tuple[int, int] = (1600, 1000)


def write_paraview_scene_script(
    script_path: Path,
    *,
    vtp_path: Path,
    vti_path: Path,
    config: ParaViewSceneConfig | None = None,
) -> Path:
    """Write a runnable pvpython script that builds the 3D activity view."""

    scene_config = config or ParaViewSceneConfig()
    screenshot_path = script_path.with_suffix(".png")
    state_path = script_path.with_suffix(".pvsm")
    script_path.write_text(
        _script_text(
            vtp_path=vtp_path.resolve(),
            vti_path=vti_path.resolve(),
            screenshot_path=screenshot_path.resolve(),
            state_path=state_path.resolve(),
            config=scene_config,
        ),
        encoding="utf-8",
    )
    return script_path


def _script_text(
    *,
    vtp_path: Path,
    vti_path: Path,
    screenshot_path: Path,
    state_path: Path,
    config: ParaViewSceneConfig,
) -> str:
    width, height = config.screenshot_size
    return f'''#!/usr/bin/env pvpython
"""ParaView 3D scene for Zigbee activity fields.

Generated by zigbee_activity_viewer. Run with:

    pvpython <this_script>.py

Outputs a screenshot and a reusable ParaView state file next to this script.
"""

import paraview.simple as pvs
from paraview.simple import *  # noqa: F403 - ParaView injects visualization proxies

POINTS_FILE = {str(vtp_path)!r}
VOLUME_FILE = {str(vti_path)!r}
SCREENSHOT_FILE = {str(screenshot_path)!r}
STATE_FILE = {str(state_path)!r}
POINT_COLOR_BY = {config.point_color_by!r}
VOLUME_COLOR_BY = {config.volume_color_by!r}


# Keep scripts deterministic when run in batch / pvpython.
pvs._DisableFirstRenderCameraReset()

# Load point cloud and activity volume produced by the exporter.
points = XMLPolyDataReader(registrationName="zigbee_activity_points", FileName=[POINTS_FILE])
volume = XMLImageDataReader(registrationName="zigbee_activity_volume", FileName=[VOLUME_FILE])

view = GetActiveViewOrCreate("RenderView")
view.ViewSize = [{width}, {height}]
view.Background = [0.03, 0.035, 0.05]
view.OrientationAxesVisibility = 1

# 3D point cloud: each point is a packet/flow positioned by time/source/destination.
points_display = Show(points, view, "GeometryRepresentation")
points_display.Representation = "Point Gaussian"
points_display.GaussianRadius = {config.point_size / 1000.0:.6f}
points_display.Opacity = {config.point_opacity:.6f}
ColorBy(points_display, ("POINTS", POINT_COLOR_BY))
points_display.SetScalarBarVisibility(view, True)
point_lut = GetColorTransferFunction(POINT_COLOR_BY)
point_lut.ApplyPreset("Viridis (matplotlib)", True)
points_display.RescaleTransferFunctionToDataRange(False, True)

# Volume: voxelized activity field for slicing or volume rendering.
volume_display = Show(volume, view, "UniformGridRepresentation")
volume_display.Representation = "Volume"
volume_display.Opacity = {config.volume_opacity:.6f}
ColorBy(volume_display, ("POINTS", VOLUME_COLOR_BY))
volume_display.SetScalarBarVisibility(view, True)
volume_lut = GetColorTransferFunction(VOLUME_COLOR_BY)
volume_lut.ApplyPreset("Cool to Warm", True)
volume_display.RescaleTransferFunctionToDataRange(False, True)

# Add an outline so the voxel field extent is visible behind the point cloud.
outline = Outline(Input=volume)
outline_display = Show(outline, view, "GeometryRepresentation")
outline_display.Representation = "Wireframe"
outline_display.LineWidth = 2.0
outline_display.DiffuseColor = [0.8, 0.8, 0.8]

# Camera tuned for a time/source/destination activity cube.
ResetCamera(view)
view.CameraPosition = [1.85, -2.15, 1.45]
view.CameraFocalPoint = [0.5, 0.5, 0.5]
view.CameraViewUp = [-0.25, 0.25, 0.94]
view.Update()

# Save artifacts so analysts can open the state interactively or view a quick render.
SaveScreenshot(SCREENSHOT_FILE, view, ImageResolution=[{width}, {height}])
SaveState(STATE_FILE)
print(f"Saved screenshot: {{SCREENSHOT_FILE}}")
print(f"Saved ParaView state: {{STATE_FILE}}")
'''
